apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: map-nats-jetstream
  annotations:
    version: v0.0.1
    description: "An application with a provider and component built to supply components with nats-jetstream publish and consumer capabilities"
spec:
  policies:
    - name: nats-kv
      type: policy.secret.wasmcloud.dev/v1alpha1
      properties:
        backend: nats-kv
        
  components:
    - name: test-component
      type: component
      properties:
        image: file://./component/build/map-jetstream-nats-component_s.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 1
        - type: link
          properties:
            target: 
              name: map-jetstream-nats
              secrets:
                - name: nats-credentials
                  properties:
                    policy: nats-kv
                    key: map-jetstream-nats-account
              config:
                - name: nats-config
                  properties:
                    url: "nats://localhost:4222" 
            namespace: mattilsynet
            package: provider-jetstream-nats
            interfaces: [jetstream-publish]
       
    - name: map-jetstream-nats
      type: capability
      properties:
        image: file://./build/map-nats-jetstream.par.gz
      traits:
        - type: link
          properties:
            target: 
              name: test-component
            source:
              secrets:
                - name: nats-credentials
                  properties:
                    policy: nats-kv
                    key: map-jetstream-nats-account
              config:
                - name: nats-config
                  properties:
                    url: "nats://localhosts:4222"
            namespace: mattilsynet
            package: provider-jetstream-nats
            interfaces: [jetstream-consumer]
                          
          
