apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: map-nats-jetstream
  annotations:
    version: v0.0.1
    description: "An application with a provider and component built to supply components with nats-jetstream publish and consumer capabilities"
spec:
  policies:
    - name: nats-kv
      type: policy.secret.wasmcloud.dev/v1alpha1
      properties:
        backend: nats-kv
        
  components:
    - name: test-component
      type: component
      properties:
        image: file://./component/build/map-jetstream-nats-component_s.wasm
        
      traits:
        - type: spreadscaler
          properties:
            instances: 1
        - type: link
          properties:
            target: 
              name: map-jetstream-nats
            namespace: mattilsynet
            package: provider-jetstream-nats
            interfaces: [jetstream-publish]
       
    - name: map-jetstream-nats
      type: capability
      properties:
        image: file://./build/map-nats-jetstream.par.gz
        
      traits:
        - type: link
          properties:
            target: 
              name: test-component
              config:
            source:
              name: test-component-source
            namespace: mattilsynet
            package: provider-jetstream-nats
            interfaces: [jetstream-consumer]
                          
            
