package mattilsynet:component-jetstream-nats;

world component {
    export mattilsynet:provider-jetstream-nats/jetstream-consumer;
    import mattilsynet:provider-jetstream-nats/jetstream-publish;
    include wasmcloud:component-go/imports@0.1.0;
}
