package mattilsynet:component-jetstream-nats;

world component {
    export mattilsynet:map-nats-jetstream/jetstream-consumer;
    import mattilsynet:map-nats-jetstream/jetstream-publish;
    include wasmcloud:component-go/imports@0.1.0;
}
